# Generated by Django 4.0.4 on 2022-06-03 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_phone_number_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
