# Generated by Django 4.0.4 on 2022-06-25 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_profile_gender_delete_extendeduser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.PositiveIntegerField(blank=True, choices=[('1', 'Select Gender'), ('2', 'Male'), ('3', 'Female'), ('4', 'Other')], null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, default='1', max_length=13, null=True),
        ),
    ]
