# Generated by Django 4.0.4 on 2022-05-30 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('poster', models.ImageField(upload_to='media/poster/')),
                ('desc', models.TextField()),
            ],
        ),
    ]
