# Generated by Django 4.0.4 on 2022-06-01 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventcard',
            name='poster',
            field=models.ImageField(upload_to='poster/'),
        ),
    ]
