# Generated by Django 4.0.4 on 2022-06-15 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_remove_addevent_address_remove_addevent_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='addevent',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
