# Generated by Django 4.0.4 on 2022-06-15 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_addevent_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addevent',
            name='slug',
        ),
    ]
