# Generated by Django 4.0.4 on 2022-06-15 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_remove_addevent_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventcard',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
