# Generated by Django 4.0.4 on 2022-06-15 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_eventcard_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addevent',
            name='event',
        ),
        migrations.RemoveField(
            model_name='addevent',
            name='user',
        ),
        migrations.AddField(
            model_name='addevent',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='addevent',
            name='event_title',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='addevent',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
