# Generated by Django 4.0.4 on 2022-06-15 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0010_addevent_event_addevent_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addevent',
            name='event',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='events.eventcard'),
        ),
        migrations.AlterField(
            model_name='addevent',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
