# Generated by Django 4.0.4 on 2022-06-15 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_alter_addevent_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addevent',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='events.eventcard'),
        ),
    ]
